name: Lint, Format, and Deploy Documentation

on:
  push:
    branches:
      - main

jobs:
  # --- ЗАДАЧА 1: Форматирование и проверка кода ---
  lint-and-format:
    # Не запускаем эту задачу для коммитов, которые делает сам бот, чтобы избежать бесконечного цикла
    if: "!contains(github.event.head_commit.message, 'chore: auto-format')"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Токен нужен для того, чтобы следующий шаг мог сделать коммит обратно в репозиторий
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Linting Tools
        run: npm install -g prettier markdownlint-cli

      - name: Auto-fix and Format Markdown Files
        run: |
          echo "Running markdownlint auto-fix..."
          markdownlint --fix ./**/*.md || true
          echo "Running Prettier auto-format..."
          prettier --write ./**/*.md

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: auto-format markdown files"
          # -------------------------------------------------------------------
          # Строка 'skip_empty_commit' была удалена, так как это поведение
          # теперь является стандартным для v5 этого экшена.
          # -------------------------------------------------------------------

  # --- ЗАДАЧA 2: Развертывание на сервере ---
  deploy:
    needs: lint-and-format
    if: "contains(github.event.head_commit.message, '[deploy]') && !contains(github.event.head_commit.message, 'chore: auto-format')"
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Connect and run the deploy script
        run: |
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "bash /var/www/my-docusaurus-site/deploy.sh"
