name: Lint, Format, and Deploy Documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  # --- ЗАДАЧА 1: Форматирование и проверка кода ---
  lint-and-format:
    if: "!contains(github.event.head_commit.message, 'chore: auto-format')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Tools and Dependencies
        run: |
          npm install -g prettier markdownlint-cli
          npm install glob

      - name: Fix Missing Front Matter
        run: node .github/scripts/fix-frontmatter.js

      - name: Auto-fix and Format Markdown Files
        run: |
          markdownlint --fix ./**/*.md || true
          prettier --write ./**/*.md

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: auto-format markdown files"

  # --- ЗАДАЧA 2: Развертывание на сервере ---
  deploy:
    needs: lint-and-format
    if: "contains(github.event.head_commit.message, '[deploy]') && !contains(github.event.head_commit.message, 'chore: auto-format')"
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Connect and run the deploy script
        run: |
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          
          # -T отключает выделение псевдо-терминала, что рекомендуется для автоматизации
          ssh -T ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "nohup bash /var/www/my-docusaurus-site/deploy.sh > /tmp/deploy.log 2>&1 < /dev/null &"
