name: Build and Deploy Documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  # --- ЗАДАЧА 1: Сборка проекта ---
  build:
    # Эта задача будет выполняться всегда, но деплой - только по условию
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Docusaurus Project
        uses: actions/checkout@v4
        # Указываем путь, куда клонировать основной проект Docusaurus
        with:
          repository: 'YOUR_GITHUB_USERNAME/my-docusaurus-site' # <--- ЗАМЕНИТЕ НА ВАШ РЕПОЗИТОРИЙ С КОДОМ
          token: ${{ secrets.PAT_FOR_CHECKOUT }} # <--- НУЖЕН Personal Access Token
          path: my-docusaurus-site

      - name: Checkout Content Repository
        uses: actions/checkout@v4
        # Указываем путь, куда клонировать репозиторий с контентом
        with:
          path: content

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'my-docusaurus-site/package-lock.json'

      - name: Sync Content
        run: |
          # Простая синхронизация контента в папку сборки
          rsync -a --delete content/documentation/ my-docusaurus-site/platform-documentation/
          rsync -a --delete content/integrations/ my-docusaurus-site/integrations/
          # ... и так далее для всех ваших папок

      - name: Install Dependencies
        working-directory: ./my-docusaurus-site
        run: npm install

      - name: Build Docusaurus Site
        working-directory: ./my-docusaurus-site
        run: npm run build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docusaurus-build
          path: my-docusaurus-site/build

  # --- ЗАДАЧА 2: Развертывание артефакта ---
  deploy:
    needs: build
    if: "contains(github.event.head_commit.message, '[deploy]')"
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: docusaurus-build
          path: build

      - name: Deploy to Server via rsync
        uses: easingthemes/ssh-deploy@v5
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDziv --delete"
          SOURCE: "build/"
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          TARGET: "/var/www/my-docusaurus-site/current" # <--- Упрощенный деплой
